/*
Aifs api

aifs api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aifsclientgo

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// AnnotationTemplateTypeApiService AnnotationTemplateTypeApi service
type AnnotationTemplateTypeApiService service

type ApiGetAnnoTemplateTypeListRequest struct {
	ctx context.Context
	ApiService *AnnotationTemplateTypeApiService
	offset *int32
	limit *int32
}

// The number of items to skip before starting to collect the result set
func (r ApiGetAnnoTemplateTypeListRequest) Offset(offset int32) ApiGetAnnoTemplateTypeListRequest {
	r.offset = &offset
	return r
}

// The numbers of items to return
func (r ApiGetAnnoTemplateTypeListRequest) Limit(limit int32) ApiGetAnnoTemplateTypeListRequest {
	r.limit = &limit
	return r
}

func (r ApiGetAnnoTemplateTypeListRequest) Execute() ([]string, *http.Response, error) {
	return r.ApiService.GetAnnoTemplateTypeListExecute(r)
}

/*
GetAnnoTemplateTypeList Get annotation template type list

Get annotation template type list

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetAnnoTemplateTypeListRequest
*/
func (a *AnnotationTemplateTypeApiService) GetAnnoTemplateTypeList(ctx context.Context) ApiGetAnnoTemplateTypeListRequest {
	return ApiGetAnnoTemplateTypeListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []string
func (a *AnnotationTemplateTypeApiService) GetAnnoTemplateTypeListExecute(r ApiGetAnnoTemplateTypeListRequest) ([]string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AnnotationTemplateTypeApiService.GetAnnoTemplateTypeList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/annotation-template-types"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
