/*
Aifs api

aifs api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aifsclientgo

import (
	"encoding/json"
)

// checks if the RawDataListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RawDataListItem{}

// RawDataListItem struct for RawDataListItem
type RawDataListItem struct {
	// the id of the raw data
	RawDataId *string `json:"rawDataId,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewRawDataListItem instantiates a new RawDataListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRawDataListItem() *RawDataListItem {
	this := RawDataListItem{}
	return &this
}

// NewRawDataListItemWithDefaults instantiates a new RawDataListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRawDataListItemWithDefaults() *RawDataListItem {
	this := RawDataListItem{}
	return &this
}

// GetRawDataId returns the RawDataId field value if set, zero value otherwise.
func (o *RawDataListItem) GetRawDataId() string {
	if o == nil || IsNil(o.RawDataId) {
		var ret string
		return ret
	}
	return *o.RawDataId
}

// GetRawDataIdOk returns a tuple with the RawDataId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDataListItem) GetRawDataIdOk() (*string, bool) {
	if o == nil || IsNil(o.RawDataId) {
		return nil, false
	}
	return o.RawDataId, true
}

// HasRawDataId returns a boolean if a field has been set.
func (o *RawDataListItem) HasRawDataId() bool {
	if o != nil && !IsNil(o.RawDataId) {
		return true
	}

	return false
}

// SetRawDataId gets a reference to the given string and assigns it to the RawDataId field.
func (o *RawDataListItem) SetRawDataId(v string) {
	o.RawDataId = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *RawDataListItem) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawDataListItem) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *RawDataListItem) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *RawDataListItem) SetUrl(v string) {
	o.Url = &v
}

func (o RawDataListItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RawDataListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RawDataId) {
		toSerialize["rawDataId"] = o.RawDataId
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableRawDataListItem struct {
	value *RawDataListItem
	isSet bool
}

func (v NullableRawDataListItem) Get() *RawDataListItem {
	return v.value
}

func (v *NullableRawDataListItem) Set(val *RawDataListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableRawDataListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableRawDataListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRawDataListItem(val *RawDataListItem) *NullableRawDataListItem {
	return &NullableRawDataListItem{value: val, isSet: true}
}

func (v NullableRawDataListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRawDataListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


