/*
Aifs api

aifs api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aifsclientgo

import (
	"encoding/json"
)

// checks if the ArtifactLocations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArtifactLocations{}

// ArtifactLocations struct for ArtifactLocations
type ArtifactLocations struct {
	DataViewId *string `json:"dataViewId,omitempty"`
	ViewType *DataViewType `json:"viewType,omitempty"`
	DataItems []S3StorageInner `json:"dataItems,omitempty"`
}

// NewArtifactLocations instantiates a new ArtifactLocations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtifactLocations() *ArtifactLocations {
	this := ArtifactLocations{}
	return &this
}

// NewArtifactLocationsWithDefaults instantiates a new ArtifactLocations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtifactLocationsWithDefaults() *ArtifactLocations {
	this := ArtifactLocations{}
	return &this
}

// GetDataViewId returns the DataViewId field value if set, zero value otherwise.
func (o *ArtifactLocations) GetDataViewId() string {
	if o == nil || IsNil(o.DataViewId) {
		var ret string
		return ret
	}
	return *o.DataViewId
}

// GetDataViewIdOk returns a tuple with the DataViewId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactLocations) GetDataViewIdOk() (*string, bool) {
	if o == nil || IsNil(o.DataViewId) {
		return nil, false
	}
	return o.DataViewId, true
}

// HasDataViewId returns a boolean if a field has been set.
func (o *ArtifactLocations) HasDataViewId() bool {
	if o != nil && !IsNil(o.DataViewId) {
		return true
	}

	return false
}

// SetDataViewId gets a reference to the given string and assigns it to the DataViewId field.
func (o *ArtifactLocations) SetDataViewId(v string) {
	o.DataViewId = &v
}

// GetViewType returns the ViewType field value if set, zero value otherwise.
func (o *ArtifactLocations) GetViewType() DataViewType {
	if o == nil || IsNil(o.ViewType) {
		var ret DataViewType
		return ret
	}
	return *o.ViewType
}

// GetViewTypeOk returns a tuple with the ViewType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactLocations) GetViewTypeOk() (*DataViewType, bool) {
	if o == nil || IsNil(o.ViewType) {
		return nil, false
	}
	return o.ViewType, true
}

// HasViewType returns a boolean if a field has been set.
func (o *ArtifactLocations) HasViewType() bool {
	if o != nil && !IsNil(o.ViewType) {
		return true
	}

	return false
}

// SetViewType gets a reference to the given DataViewType and assigns it to the ViewType field.
func (o *ArtifactLocations) SetViewType(v DataViewType) {
	o.ViewType = &v
}

// GetDataItems returns the DataItems field value if set, zero value otherwise.
func (o *ArtifactLocations) GetDataItems() []S3StorageInner {
	if o == nil || IsNil(o.DataItems) {
		var ret []S3StorageInner
		return ret
	}
	return o.DataItems
}

// GetDataItemsOk returns a tuple with the DataItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactLocations) GetDataItemsOk() ([]S3StorageInner, bool) {
	if o == nil || IsNil(o.DataItems) {
		return nil, false
	}
	return o.DataItems, true
}

// HasDataItems returns a boolean if a field has been set.
func (o *ArtifactLocations) HasDataItems() bool {
	if o != nil && !IsNil(o.DataItems) {
		return true
	}

	return false
}

// SetDataItems gets a reference to the given []S3StorageInner and assigns it to the DataItems field.
func (o *ArtifactLocations) SetDataItems(v []S3StorageInner) {
	o.DataItems = v
}

func (o ArtifactLocations) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArtifactLocations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataViewId) {
		toSerialize["dataViewId"] = o.DataViewId
	}
	if !IsNil(o.ViewType) {
		toSerialize["viewType"] = o.ViewType
	}
	if !IsNil(o.DataItems) {
		toSerialize["dataItems"] = o.DataItems
	}
	return toSerialize, nil
}

type NullableArtifactLocations struct {
	value *ArtifactLocations
	isSet bool
}

func (v NullableArtifactLocations) Get() *ArtifactLocations {
	return v.value
}

func (v *NullableArtifactLocations) Set(val *ArtifactLocations) {
	v.value = val
	v.isSet = true
}

func (v NullableArtifactLocations) IsSet() bool {
	return v.isSet
}

func (v *NullableArtifactLocations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtifactLocations(val *ArtifactLocations) *NullableArtifactLocations {
	return &NullableArtifactLocations{value: val, isSet: true}
}

func (v NullableArtifactLocations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtifactLocations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


