/*
Aifs api

aifs api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aifsclientgo

import (
	"encoding/json"
)

// checks if the MergeDataViewsSuccessResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MergeDataViewsSuccessResp{}

// MergeDataViewsSuccessResp struct for MergeDataViewsSuccessResp
type MergeDataViewsSuccessResp struct {
	DataViewId *string `json:"dataViewId,omitempty"`
}

// NewMergeDataViewsSuccessResp instantiates a new MergeDataViewsSuccessResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMergeDataViewsSuccessResp() *MergeDataViewsSuccessResp {
	this := MergeDataViewsSuccessResp{}
	return &this
}

// NewMergeDataViewsSuccessRespWithDefaults instantiates a new MergeDataViewsSuccessResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMergeDataViewsSuccessRespWithDefaults() *MergeDataViewsSuccessResp {
	this := MergeDataViewsSuccessResp{}
	return &this
}

// GetDataViewId returns the DataViewId field value if set, zero value otherwise.
func (o *MergeDataViewsSuccessResp) GetDataViewId() string {
	if o == nil || IsNil(o.DataViewId) {
		var ret string
		return ret
	}
	return *o.DataViewId
}

// GetDataViewIdOk returns a tuple with the DataViewId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeDataViewsSuccessResp) GetDataViewIdOk() (*string, bool) {
	if o == nil || IsNil(o.DataViewId) {
		return nil, false
	}
	return o.DataViewId, true
}

// HasDataViewId returns a boolean if a field has been set.
func (o *MergeDataViewsSuccessResp) HasDataViewId() bool {
	if o != nil && !IsNil(o.DataViewId) {
		return true
	}

	return false
}

// SetDataViewId gets a reference to the given string and assigns it to the DataViewId field.
func (o *MergeDataViewsSuccessResp) SetDataViewId(v string) {
	o.DataViewId = &v
}

func (o MergeDataViewsSuccessResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MergeDataViewsSuccessResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataViewId) {
		toSerialize["dataViewId"] = o.DataViewId
	}
	return toSerialize, nil
}

type NullableMergeDataViewsSuccessResp struct {
	value *MergeDataViewsSuccessResp
	isSet bool
}

func (v NullableMergeDataViewsSuccessResp) Get() *MergeDataViewsSuccessResp {
	return v.value
}

func (v *NullableMergeDataViewsSuccessResp) Set(val *MergeDataViewsSuccessResp) {
	v.value = val
	v.isSet = true
}

func (v NullableMergeDataViewsSuccessResp) IsSet() bool {
	return v.isSet
}

func (v *NullableMergeDataViewsSuccessResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMergeDataViewsSuccessResp(val *MergeDataViewsSuccessResp) *NullableMergeDataViewsSuccessResp {
	return &NullableMergeDataViewsSuccessResp{value: val, isSet: true}
}

func (v NullableMergeDataViewsSuccessResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMergeDataViewsSuccessResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


